name: Make artifacts

on: workflow_dispatch

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v4
      - name: Install gcc and Make
        run: sudo apt install -y gcc make
      - name: Build project
        run: make
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: tetris

          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: dist/tetris
