name: Make artifacts

on: workflow_dispatch

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v4
      - name: Install gcc and Make
        run: sudo apt install -y gcc make
      - name: Build project
        run: make deb
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tetris_deb
          path: dist/packages/linux/deb/tetris_1.0-1_amd64.deb
  build-win:
    runs-on: windows-latest
    steps:
      - name: Download code
        uses: actions/checkout@v4
      - name: Install Make
        run: choco install make
      - name: Build project
        run: make win
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tetris_win
          path: dist/packages/windows/tetris.exe
